# Site settings
author: Kal
title: A Cluttered Workbench
header-img: img/home-bg.png
email: kalmegati@gmail.com
copyright_name: Kal
description: > # this means to ignore newlines until "baseurl:"
  conception before clutter, clutter until complete
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KalMegati

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
